package com.danieldk.splatevpn.ui.theme

import androidx.compose.runtime.Composable
import androidx.compose.runtime.compositionLocalOf
import androidx.compose.ui.platform.LocalConfiguration
import java.util.Locale

class AppStrings(
    // Common
    val appName: String,
    val cancel: String,
    val save: String,
    val delete: String,
    val close: String,
    val add: String,
    val refresh: String,
    val edit: String,

    // Navigation Tabs
    val tabControl: String,
    val tabNodes: String,
    val tabRouting: String,
    val tabConfig: String,

    // Home Screen
    val standbyUnprotected: String,
    val encryptedSession: String,
    val resolvingLocation: String,
    val protectedGateway: String,
    val egressIp: String,
    val ping: String,
    val download: String,
    val upload: String,
    val routingProfile: String,
    val smartRoute: String,
    val smartRouteDesc: String,
    val globalTunnel: String,
    val globalTunnelDesc: String,
    val activeGateway: String,
    val autoFastest: String,
    val pinging: String,
    val noServerSelected: String,

    // Servers Screen
    val networkNodes: String,
    val availableNodes: String,
    val pingAll: String,
    val pasteLink: String,
    val subs: String,
    val allChip: String,
    val builtinChip: String,
    val noServersFound: String,
    val noServersInFilter: String,
    val addServerTitle: String,
    val addServerPrompt: String,
    val serverAddedSuccess: String,
    val invalidLinkFormat: String,
    val editServerTitle: String,
    val serverUpdatedSuccess: String,

    // Server Fields
    val fieldName: String,
    val fieldProtocol: String,
    val fieldAddress: String,
    val fieldPort: String,
    val fieldNetwork: String,
    val fieldSecurity: String,
    val fieldSni: String,
    val fieldPath: String,
    val fieldHost: String,
    val fieldUuid: String,
    val fieldPublicKey: String,
    val fieldShortId: String,
    val fieldSpiderX: String,
    val fieldFingerprint: String,

    // Apps Screen
    val appRoutingTitle: String,
    val proxiedAppsCount: String,
    val proxyModeAll: String,
    val proxyModeAllDesc: String,
    val proxyModeSelected: String,
    val proxyModeSelectedDesc: String,
    val searchApps: String,
    val statusProxied: String,
    val statusDirect: String,

    // Settings Screen
    val settingsTitle: String,
    val settingsSubtitle: String,
    val sectionAppearance: String,
    val themeTitle: String,
    val themeSubtitle: String,
    val themeDark: String,
    val themeAmoled: String,
    val themeLight: String,
    val themeSystem: String,
    val languageTitle: String,
    val languageSubtitle: String,
    val langRu: String,
    val langEn: String,
    val langSystem: String,

    val sectionAutomation: String,
    val autoSelectTitle: String,
    val autoSelectSubtitle: String,
    val autoUpdateTitle: String,
    val autoUpdateSubtitle: String,
    val intervalOff: String,
    val interval6h: String,
    val interval12h: String,
    val interval24h: String,
    val updateAllSubsNow: String,
    val updating: String,
    val updatedCount: String,

    val sectionRouting: String,
    val dnsProviderTitle: String,
    val dnsProviderSubtitle: String,
    val xhttpModeTitle: String,
    val xhttpModeSubtitle: String,
    val fakeDnsTitle: String,
    val fakeDnsSubtitle: String,
    val blockQuicTitle: String,
    val blockQuicSubtitle: String,
    val sniffingTitle: String,
    val sniffingSubtitle: String,
    val blockIpv6Title: String,
    val blockIpv6Subtitle: String,

    val sectionCore: String,
    val coreVersion: String,
    val coreArch: String,
    val coreTunnel: String,
    val coreProtocols: String,
    val coreFakeDns: String,

    val sectionDiagnostics: String,
    val diagnosticsDesc: String,
    val openLogsButton: String,
    val logsDialogTitle: String,
    val copyReport: String,
    val shareReport: String,
    val clearLogs: String,
    val reportCopied: String
)

val RussianStrings = AppStrings(
    appName = "Splate VPN",
    cancel = "Отмена",
    save = "Сохранить",
    delete = "Удалить",
    close = "Закрыть",
    add = "Добавить",
    refresh = "Обновить",
    edit = "Редактировать",

    tabControl = "КОНТРОЛЬ",
    tabNodes = "УЗЛЫ",
    tabRouting = "МАРШРУТЫ",
    tabConfig = "НАСТРОЙКИ",

    standbyUnprotected = "ОЖИДАНИЕ • НЕ ЗАЩИЩЕНО",
    encryptedSession = "ЗАЩИЩЕНО • %s",
    resolvingLocation = "ОПРЕДЕЛЕНИЕ ЛОКАЦИИ...",
    protectedGateway = "ЗАЩИЩЕННЫЙ ШЛЮЗ",
    egressIp = "ВЫХОД: %s",
    ping = "ПИНГ",
    download = "СКАЧИВАНИЕ",
    upload = "ОТПРАВКА",
    routingProfile = "ПРОФИЛЬ МАРШРУТИЗАЦИИ",
    smartRoute = "УМНЫЙ МАРШРУТ",
    smartRouteDesc = "Обход блокировок (RU напрямую)",
    globalTunnel = "ПОЛНЫЙ ТУННЕЛЬ",
    globalTunnelDesc = "100% трафика через VPN",
    activeGateway = "АКТИВНЫЙ ШЛЮЗ",
    autoFastest = "БЫСТРЫЙ",
    pinging = "ПИНГ...",
    noServerSelected = "Сервер не выбран",

    networkNodes = "СЕТЕВЫЕ УЗЛЫ",
    availableNodes = "ДОСТУПНО: %d / %d",
    pingAll = "ПИНГ ВСЕХ",
    pasteLink = "ВСТАВИТЬ ССЫЛКУ",
    subs = "ПОДПИСКИ (%d)",
    allChip = "Все (%d)",
    builtinChip = "⚡ Встроенные",
    noServersFound = "Нет доступных серверов.\nДобавьте ссылку или подписку.",
    noServersInFilter = "В данной категории нет серверов.",
    addServerTitle = "Добавить сервер",
    addServerPrompt = "Вставьте vless://, trojan://, vmess:// или ss:// ссылку:",
    serverAddedSuccess = "Сервер успешно добавлен!",
    invalidLinkFormat = "Неверный формат ссылки",
    editServerTitle = "Редактирование параметров узла",
    serverUpdatedSuccess = "Параметры узла сохранены!",

    fieldName = "Название узла",
    fieldProtocol = "Протокол",
    fieldAddress = "Адрес / IP",
    fieldPort = "Порт",
    fieldNetwork = "Транспорт / Сеть (type)",
    fieldSecurity = "Безопасность (security)",
    fieldSni = "SNI домен",
    fieldPath = "Путь (path / serviceName)",
    fieldHost = "Host заголовок",
    fieldUuid = "UUID / Пароль",
    fieldPublicKey = "Публичный ключ (pbk / Reality)",
    fieldShortId = "Short ID (sid)",
    fieldSpiderX = "SpiderX (spx)",
    fieldFingerprint = "Fingerprint (fp)",

    appRoutingTitle = "МАРШРУТИЗАЦИЯ ПРИЛОЖЕНИЙ",
    proxiedAppsCount = "ПРИЛОЖЕНИЯ В VPN: %d / %d",
    proxyModeAll = "Все приложения",
    proxyModeAllDesc = "Весь трафик устройства направляется через туннель",
    proxyModeSelected = "Выбранные приложения",
    proxyModeSelectedDesc = "Только отмеченные приложения идут через VPN",
    searchApps = "Поиск приложений...",
    statusProxied = "В VPN",
    statusDirect = "НАПРЯМУЮ",

    settingsTitle = "Настройки",
    settingsSubtitle = "Конфигурация обхода блокировок, оформления и ядра",
    sectionAppearance = "ОФОРМЛЕНИЕ И ИНТЕРФЕЙС",
    themeTitle = "Тема оформления",
    themeSubtitle = "Цветовая палитра и визуальный стиль",
    themeDark = "Тёмная",
    themeAmoled = "AMOLED",
    themeLight = "Светлая",
    themeSystem = "Системная",
    languageTitle = "Язык приложения",
    languageSubtitle = "Выбор языка интерфейса",
    langRu = "Русский",
    langEn = "English",
    langSystem = "Системный",

    sectionAutomation = "АВТОМАТИЗАЦИЯ И ПОДПИСКИ",
    autoSelectTitle = "Автовыбор сервера",
    autoSelectSubtitle = "Автоматически проверять пинг и подключаться к самому быстрому серверу.",
    autoUpdateTitle = "Автообновление подписок",
    autoUpdateSubtitle = "Периодичность фонового обновления серверов",
    intervalOff = "Выкл",
    interval6h = "6 ч",
    interval12h = "12 ч",
    interval24h = "24 ч",
    updateAllSubsNow = "Обновить все подписки сейчас",
    updating = "Обновление...",
    updatedCount = "Обновлено подписок: %d",

    sectionRouting = "МАРШРУТИЗАЦИЯ И ОБХОД БЛОКИРОВОК (РКН)",
    dnsProviderTitle = "DNS Провайдер (DoH + UDP)",
    dnsProviderSubtitle = "Защита от подмены и отслеживания DNS-запросов",
    xhttpModeTitle = "Режим XHTTP (SplitHTTP)",
    xhttpModeSubtitle = "stream-one оптимизирован для голосовых в Telegram",
    fakeDnsTitle = "Strict FakeDNS (198.18.0.0/15)",
    fakeDnsSubtitle = "Локальный пул Fake-IP. Защита от DNS-spoofing со стороны ТСПУ/РКН.",
    blockQuicTitle = "Блокировка QUIC (UDP 443)",
    blockQuicSubtitle = "Принудительный fallback на TLS. Защищает YouTube, Discord и браузеры.",
    sniffingTitle = "Сниффинг доменов (RouteOnly)",
    sniffingSubtitle = "Распознает SNI для правил, не искажая прямые MTProto-пакеты Telegram.",
    blockIpv6Title = "Защита от утечек IPv6",
    blockIpv6Subtitle = "Блокирует нешифрованный трафик IPv6 для исключения раскрытия адреса.",

    sectionCore = "ЯДРО XRAY-CORE",
    coreVersion = "Версия ядра",
    coreArch = "Архитектура",
    coreTunnel = "Туннель",
    coreProtocols = "Протоколы",
    coreFakeDns = "FakeDNS Pool",

    sectionDiagnostics = "ДИАГНОСТИКА И ОТЛАДКА",
    diagnosticsDesc = "Журнал работы ядра Xray, событий VPN и сетевых ошибок. Позволяет скопировать или отправить диагностический отчёт.",
    openLogsButton = "Открыть журнал и логи ошибок",
    logsDialogTitle = "Журнал событий и логи ядра",
    copyReport = "Скопировать отчёт",
    shareReport = "Поделиться",
    clearLogs = "Очистить логи",
    reportCopied = "Отчёт скопирован в буфер обмена!"
)

val EnglishStrings = AppStrings(
    appName = "Splate VPN",
    cancel = "Cancel",
    save = "Save",
    delete = "Delete",
    close = "Close",
    add = "Add",
    refresh = "Refresh",
    edit = "Edit",

    tabControl = "CONTROL",
    tabNodes = "NODES",
    tabRouting = "ROUTING",
    tabConfig = "CONFIG",

    standbyUnprotected = "STANDBY • UNPROTECTED",
    encryptedSession = "ENCRYPTED • %s",
    resolvingLocation = "RESOLVING LOCATION...",
    protectedGateway = "PROTECTED GATEWAY",
    egressIp = "EGRESS: %s",
    ping = "PING",
    download = "DOWNLOAD",
    upload = "UPLOAD",
    routingProfile = "ROUTING PROFILE",
    smartRoute = "SMART ROUTE",
    smartRouteDesc = "Bypass local RU services",
    globalTunnel = "GLOBAL TUNNEL",
    globalTunnelDesc = "Strict 100% Proxy Tunnel",
    activeGateway = "ACTIVE GATEWAY",
    autoFastest = "FASTEST",
    pinging = "PINGING...",
    noServerSelected = "No server selected",

    networkNodes = "NETWORK NODES",
    availableNodes = "AVAILABLE: %d / %d",
    pingAll = "PING ALL",
    pasteLink = "PASTE LINK",
    subs = "SUBS (%d)",
    allChip = "All (%d)",
    builtinChip = "⚡ Built-in",
    noServersFound = "No servers available.\nAdd a link or subscription.",
    noServersInFilter = "No servers in this category.",
    addServerTitle = "Add Server",
    addServerPrompt = "Paste vless://, trojan://, vmess://, or ss:// link:",
    serverAddedSuccess = "Server added successfully!",
    invalidLinkFormat = "Invalid link format",
    editServerTitle = "Edit Server Parameters",
    serverUpdatedSuccess = "Server parameters updated!",

    fieldName = "Node Name",
    fieldProtocol = "Protocol",
    fieldAddress = "Address / IP",
    fieldPort = "Port",
    fieldNetwork = "Network Transport (type)",
    fieldSecurity = "Security Mode",
    fieldSni = "SNI Domain",
    fieldPath = "Path (path / serviceName)",
    fieldHost = "Host Header",
    fieldUuid = "UUID / Password",
    fieldPublicKey = "Public Key (pbk / Reality)",
    fieldShortId = "Short ID (sid)",
    fieldSpiderX = "SpiderX (spx)",
    fieldFingerprint = "Fingerprint (fp)",

    appRoutingTitle = "APP ROUTING",
    proxiedAppsCount = "PROXIED APPS: %d / %d",
    proxyModeAll = "All Applications",
    proxyModeAllDesc = "All device traffic is routed through VPN tunnel",
    proxyModeSelected = "Selected Applications",
    proxyModeSelectedDesc = "Only selected applications are routed through VPN",
    searchApps = "Search applications...",
    statusProxied = "PROXIED",
    statusDirect = "DIRECT",

    settingsTitle = "Settings",
    settingsSubtitle = "Censorship bypass, UI appearance and core engine config",
    sectionAppearance = "INTERFACE & APPEARANCE",
    themeTitle = "App Theme",
    themeSubtitle = "Visual style and color palette",
    themeDark = "Dark",
    themeAmoled = "AMOLED",
    themeLight = "Light",
    themeSystem = "System",
    languageTitle = "Language",
    languageSubtitle = "Interface language selection",
    langRu = "Русский",
    langEn = "English",
    langSystem = "System",

    sectionAutomation = "AUTOMATION & SUBSCRIPTIONS",
    autoSelectTitle = "Auto-select Server",
    autoSelectSubtitle = "Automatically test latency and select the fastest node.",
    autoUpdateTitle = "Auto-update Subscriptions",
    autoUpdateSubtitle = "Frequency of background server list synchronization",
    intervalOff = "Off",
    interval6h = "6 h",
    interval12h = "12 h",
    interval24h = "24 h",
    updateAllSubsNow = "Update all subscriptions now",
    updating = "Updating...",
    updatedCount = "Updated subscriptions: %d",

    sectionRouting = "ROUTING & ANTI-CENSORSHIP",
    dnsProviderTitle = "DNS Provider (DoH + UDP)",
    dnsProviderSubtitle = "Protection against DNS spoofing and ISP tracking",
    xhttpModeTitle = "XHTTP (SplitHTTP) Mode",
    xhttpModeSubtitle = "stream-one is optimized for voice and streaming traffic",
    fakeDnsTitle = "Strict FakeDNS (198.18.0.0/15)",
    fakeDnsSubtitle = "Local Fake-IP pool. Prevents censorship DNS poisoning.",
    blockQuicTitle = "Block QUIC (UDP 443)",
    blockQuicSubtitle = "Forces fallback to TLS. Unblocks YouTube, Discord, and browsers.",
    sniffingTitle = "Domain Sniffing (RouteOnly)",
    sniffingSubtitle = "Sniffs SNI for routing rules without breaking MTProto packets.",
    blockIpv6Title = "IPv6 Leak Protection",
    blockIpv6Subtitle = "Blocks unencrypted IPv6 to prevent real address leaks.",

    sectionCore = "XRAY CORE ENGINE",
    coreVersion = "Core Version",
    coreArch = "Architecture",
    coreTunnel = "Tunnel Engine",
    coreProtocols = "Protocols",
    coreFakeDns = "FakeDNS Pool",

    sectionDiagnostics = "DIAGNOSTICS & DEBUGGING",
    diagnosticsDesc = "Logs of Xray core execution, VPN events and connection errors.",
    openLogsButton = "Open Logs & Error Journal",
    logsDialogTitle = "System Events & Core Logs",
    copyReport = "Copy Report",
    shareReport = "Share",
    clearLogs = "Clear Logs",
    reportCopied = "Report copied to clipboard!"
)

val LocalAppStrings = compositionLocalOf<AppStrings> { RussianStrings }

@Composable
fun getStringsForLanguage(languageSetting: String): AppStrings {
    return when (languageSetting.lowercase()) {
        "ru" -> RussianStrings
        "en" -> EnglishStrings
        else -> {
            val systemLocale = LocalConfiguration.current.locales.get(0) ?: Locale.getDefault()
            if (systemLocale.language.startsWith("ru", ignoreCase = true)) {
                RussianStrings
            } else {
                EnglishStrings
            }
        }
    }
}
